import { useEffect, useState } from 'react';
import { api } from '../lib/api';
type Config = { baseUrl: string; model: string; keyPresent: boolean; ai: boolean };
export default function AiSettings({ changed, open }: { changed: () => void; open?: boolean }) {
  const [config, setConfig] = useState<Config>(); const [key, setKey] = useState(''); const [clearKey, setClearKey] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [models, setModels] = useState<string[]>([]);
  useEffect(() => { let alive = true; void api<Config>('/ai-config').then(value => { if (alive) setConfig(value); }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, []);
  return <details className="mt-3 text-xs" open={open}><summary className="cursor-pointer text-vs-link">Configurar modelo de IA</summary><p className="text-vs-dim mt-2">Use um servidor compatível com OpenAI, como Ollama local. O código selecionado será enviado ao endereço configurado.</p>{config && <form className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); setBusy(true); setError(''); void api<Config>('/ai-config', 'POST', { baseUrl: config.baseUrl, model: config.model, key, clearKey }).then(value => { setConfig(value); setKey(''); setClearKey(false); changed(); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}><label className="block">Endpoint<input className="field w-full mt-1" placeholder="http://127.0.0.1:11434/v1" value={config.baseUrl} onChange={e => setConfig({ ...config, baseUrl: e.target.value })} /></label><label className="block">Modelo<input list="cm-models" className="field w-full mt-1" placeholder="Nome do modelo instalado" value={config.model} onChange={e => setConfig({ ...config, model: e.target.value })} /><datalist id="cm-models">{models.map(model => <option value={model} key={model} />)}</datalist></label><button type="button" className="btn-secondary text-xs" onClick={() => void api<{ models: string[] }>('/ai-config/models').then(value => setModels(value.models)).catch(e => setError(e.message))}>Listar modelos do endpoint salvo</button><label className="block">Chave (opcional)<input className="field w-full mt-1" type="password" autoComplete="off" placeholder={config.keyPresent ? 'Chave salva — deixe vazio para manter' : 'Sem chave salva'} value={key} onChange={e => setKey(e.target.value)} /></label>{config.keyPresent && <label className="flex gap-2"><input type="checkbox" checked={clearKey} onChange={e => setClearKey(e.target.checked)} />Remover chave salva</label>}<button className="btn-secondary text-xs" disabled={busy}>Salvar configuração</button><p className="text-vs-dim">A chave fica em arquivo local; não compartilhe sua pasta .code-makers.</p></form>}{error && <p className="error-banner mt-2">{error}</p>}</details>;
}
